"""empty message

Revision ID: 07435c46e52b
Revises: a2ca2ca4d53f
Create Date: 2025-05-03 14:11:30.810744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07435c46e52b'
down_revision: Union[str, None] = 'a2ca2ca4d53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'deleted_at')
    # ### end Alembic commands ###
