"""empty message

Revision ID: 09a78aeb4487
Revises: 139afce5a5d3
Create Date: 2025-04-12 18:36:24.566489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09a78aeb4487'
down_revision: Union[str, None] = '139afce5a5d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('name', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'name')
    # ### end Alembic commands ###
