"""empty message

Revision ID: 1937600eff91
Revises: bedf1890ca0e
Create Date: 2025-04-14 05:06:37.166935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1937600eff91'
down_revision: Union[str, None] = 'bedf1890ca0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webpush_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', mysql.TEXT(), nullable=False),
    sa.Column('p256dh', mysql.TEXT(), nullable=False),
    sa.Column('auth', mysql.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webpush_subscription_id'), 'webpush_subscription', ['id'], unique=False)
    op.create_index(op.f('ix_webpush_subscription_user_id'), 'webpush_subscription', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webpush_subscription_user_id'), table_name='webpush_subscription')
    op.drop_index(op.f('ix_webpush_subscription_id'), table_name='webpush_subscription')
    op.drop_table('webpush_subscription')
    # ### end Alembic commands ###
