"""empty message

Revision ID: 43ba378f2dc4
Revises: 5fbdf09af201
Create Date: 2025-04-13 11:07:55.396156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43ba378f2dc4'
down_revision: Union[str, None] = '5fbdf09af201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_limit', sa.Integer(), server_default='3', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_limit')
    # ### end Alembic commands ###
