"""empty message

Revision ID: 5970dafefbe7
Revises: 576d576402ec
Create Date: 2025-05-03 20:00:15.230852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5970dafefbe7'
down_revision: Union[str, None] = '576d576402ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'member_limit',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'member_limit',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
