"""empty message

Revision ID: a2ca2ca4d53f
Revises: acb77cf578ce
Create Date: 2025-04-21 21:29:11.644612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ca2ca4d53f'
down_revision: Union[str, None] = 'acb77cf578ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organization_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='organizationrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_organization_user')
    )
    op.add_column('account', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('account', sa.Column('is_public', sa.Boolean(), server_default='0', nullable=True))
    op.create_index(op.f('ix_account_organization_id'), 'account', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'account', 'organization', ['organization_id'], ['id'])
    op.add_column('user', sa.Column('organization_limit', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'organization_limit')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_index(op.f('ix_account_organization_id'), table_name='account')
    op.drop_column('account', 'is_public')
    op.drop_column('account', 'organization_id')
    op.drop_table('organization_member')
    op.drop_table('organization')
    # ### end Alembic commands ###
