"""empty message

Revision ID: cfc2ff93d043
Revises: 09a78aeb4487
Create Date: 2025-04-12 18:40:54.308323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc2ff93d043'
down_revision: Union[str, None] = '09a78aeb4487'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('list_order', sa.Integer(), nullable=True))
    op.drop_index('account_number', table_name='account')
    op.create_index(op.f('ix_account_account_number'), 'account', ['account_number'], unique=True)
    op.create_index(op.f('ix_account_list_order'), 'account', ['list_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_list_order'), table_name='account')
    op.drop_index(op.f('ix_account_account_number'), table_name='account')
    op.create_index('account_number', 'account', ['account_number'], unique=True)
    op.drop_column('account', 'list_order')
    # ### end Alembic commands ###
