version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pxdb
      MYSQL_USER: pxproto
      MYSQL_PASSWORD: pxproto
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --skip-log-error  # Игнорировать ошибки, если данные уже есть
volumes:
  mysql-data: